# --- Main Colors ---
background            #17130b
foreground            #ebe1d4
cursor                #ebe1d4
cursor_text_color     #17130b

selection_background  #53452a
selection_foreground  #f6e0bb

url_color             #b2cfa8

# --- ANSI Colors ---
color0                #17130b
color1                #ffb4ab
color2                #b2cfa8
color3                #d9c4a0
color4                #ebc06c
color5                #b2cfa8
color6                #d9c4a0
color7                #ebe1d4

color8                #4d4639
color9                #93000a
color10               #344d2f
color11               #53452a
color12               #5d4200
color13               #53452a
color14               #344d2f
color15               #d1c5b4

# --- Starship Prompt Bubbles ---
color255              #5d4200
color254              #ebc06c
color253              #53452a
color252              #d9c4a0
color251              #344d2f
color250              #b2cfa8
color249              #93000a
color248              #ffb4ab

color232              #ffdea3
color233              #402d00
color234              #f6e0bb
color235              #3b2f15
color236              #cdebc3
color237              #1e361b
color238              #ffdad6
color239              #690005
color240              #ffdea3

# Matched with unthemed light/dark
color243              #ebc06c
color244              #ffb4ab
color245              #4d4639

# --- UI Elements ---
active_tab_foreground   #402d00
active_tab_background   #ebc06c
inactive_tab_foreground #ffdea3
inactive_tab_background #5d4200

active_border_color     #ebc06c
inactive_border_color   #9a8f80

# --- Marks ---
mark1_foreground        #261900
mark1_background        #ffdea3
mark2_foreground        #251a04
mark2_background        #f6e0bb
mark3_foreground        #092008
mark3_background        #cdebc3
