general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1
    on-timeout = hyprctl keyword monitor "eDP-1,disable"
    on-resume = hyprctl keyword monitor "eDP-1,preferred,auto,1"
}
